#!/bin/bash

send_msg () {
  val=`cat notes/$1.md`
  echo 'payload={"icon_emoji": ":japanese_goblin:", "username": "webhook" , "channel": "@sshojiro" , "text": "'"$val"'"}' \
    | sed -e 's/$/ \\n/g' > notes/$1.json
  curl -X POST \
    -d @notes/$1.json \
    https://hooks.slack.com/services/$(cat config/.token) # web-hook url
  rm notes/$1.json
}
if [ -z ${1+x} ]; then
  DATE=`date +%Y-%m-%d`;
else
  DATE=$(echo $1);
fi
send_msg $DATE 
